### ISSUE TITLE
[Epic] Configure a login flow for the website

### ISSUE THREAD

**Issue by MgenGlder** [dearborn-coding-club/website-base-auth#7]
## Description
We want a way to login to the app using an inbuilt authentication server. This should connect to the front end and have a default set of permissions that allow the user to see the entire website.

### Tasklist
- [x] Build an auth server
- [x] Configure JWT creation and refreshing
- [x] Build front end interaction with auth server to authenticate
- [ ] Block notes page on front end so only authenticated users can see it

**Comment by MgenGlder** [comment]
This was completed in https://github.com/dearborn-coding-club/website-base-auth/pull/20. Closing.
